language: python
python: 
- "3.5.2"
services:
- postgresql
sudo: false
cache: pip3
install:
- pip install -r requirements.txt
before_script:
  - psql -c 'create database fast-food-fast;' -U postgres
script:
- pytest --cov=.
- coverage
- coverage report
- coveralls
after_success:
- coveralls