language: python
python: 
- "3.5.2"
services:
- postgresql
env:
  - TRAVIS = True
cache: pip3
install:
- pip install -r requirements.txt
before_script:
  - psql -c 'create database fastfoodfast;' -U postgres
script:
- pytest --cov=.
after_success:
- coveralls